### ISSUE TITLE
add optional reconciliation id to the payload

### ISSUE THREAD

**Issue by unieagle** [killbill/killbill-cybersource-plugin#19]
Cybersource will generate reconciliation id and pass it to gateways and also put it in the response to upstream.
Then this reconciliation id will be present in later statements from bank side, and allow us link the records in the statements to the original transactions.

However, if the transaction failed, there is no reconciliation in the response payload. And have confirmed with Cybersource team, they won't provide this number in the response for failed transactions.
This causes a problem when we need to do analysis on the auth failures (want to know the reason of failures)

Thus, Cybersource team provides another workaround that this reconciliation actually can either generate by Cybersource or we can pass it as request payload to them.

So, I'm going to make the code changes here to allow upstream passing `reconciliation_id` to Cybersource plugin and pass this id in the request payload to Cybersource.

@pierre @sbrossie any suggestion or concern on this? thanks!

**Comment by pierre** [comment]
Sounds good, can you prepare a PR for review?

**Comment by unieagle** [comment]
thanks! sure, will do that.

**Comment by pierre** [comment]
@unieagle I am unable to release the plugin due to failing tests, could you take a look?

https://travis-ci.org/killbill/killbill-cybersource-plugin/builds/268267074


```
Failures:
  1) Killbill::Cybersource::PaymentPlugin with reconciliation id successful transactions should send passedin reconciliation id to Cybersource
     Failure/Error: gw_response.params_reconciliation_id.should == '1F16A6C017F12C15'
       expected: "1F16A6C017F12C15"
            got: "78591468H6QMUEVQ" (using ==)
     # ./spec/cybersource/remote/integration_spec.rb:794:in `(root)'
```
